// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package models

import (
	"github.com/google/uuid"
)

// Photo defines model for Photo.
type Photo struct {
	UUID uuid.UUID `json:"uuid"`
}
