version: '3.4'
services:
  # postgres is our primary data store
  postgres:
    image: postgres
    volumes:
      - ./golang/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres